// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxchartutil.proxies;

public class MxEntities
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mxEntitiesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxChartUtil.MxEntities";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ModuleName("ModuleName"),
		AttributeName("AttributeName");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MxEntities(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MxChartUtil.MxEntities"));
	}

	protected MxEntities(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mxEntitiesMendixObject)
	{
		if (mxEntitiesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MxChartUtil.MxEntities", mxEntitiesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MxChartUtil.MxEntities");

		this.mxEntitiesMendixObject = mxEntitiesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MxEntities.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static mxchartutil.proxies.MxEntities initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mxchartutil.proxies.MxEntities.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static mxchartutil.proxies.MxEntities initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxchartutil.proxies.MxEntities(context, mendixObject);
	}

	public static mxchartutil.proxies.MxEntities load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxchartutil.proxies.MxEntities.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ModuleName
	 */
	public final java.lang.String getModuleName()
	{
		return getModuleName(getContext());
	}

	/**
	 * @param context
	 * @return value of ModuleName
	 */
	public final java.lang.String getModuleName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ModuleName.toString());
	}

	/**
	 * Set value of ModuleName
	 * @param modulename
	 */
	public final void setModuleName(java.lang.String modulename)
	{
		setModuleName(getContext(), modulename);
	}

	/**
	 * Set value of ModuleName
	 * @param context
	 * @param modulename
	 */
	public final void setModuleName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String modulename)
	{
		getMendixObject().setValue(context, MemberNames.ModuleName.toString(), modulename);
	}

	/**
	 * @return value of AttributeName
	 */
	public final java.lang.String getAttributeName()
	{
		return getAttributeName(getContext());
	}

	/**
	 * @param context
	 * @return value of AttributeName
	 */
	public final java.lang.String getAttributeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AttributeName.toString());
	}

	/**
	 * Set value of AttributeName
	 * @param attributename
	 */
	public final void setAttributeName(java.lang.String attributename)
	{
		setAttributeName(getContext(), attributename);
	}

	/**
	 * Set value of AttributeName
	 * @param context
	 * @param attributename
	 */
	public final void setAttributeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attributename)
	{
		getMendixObject().setValue(context, MemberNames.AttributeName.toString(), attributename);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mxEntitiesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxchartutil.proxies.MxEntities that = (mxchartutil.proxies.MxEntities) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MxChartUtil.MxEntities";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
