// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class DynamicMultiSeriesChart extends mxchartutil.proxies.MultiSeriesChart
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.DynamicMultiSeriesChart";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OqlQuery("OqlQuery"),
		CreationDate("CreationDate"),
		Name("Name"),
		MultiSeriesChart_MultiSeriesDataset("MxChartUtil.MultiSeriesChart_MultiSeriesDataset");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DynamicMultiSeriesChart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Main.DynamicMultiSeriesChart"));
	}

	protected DynamicMultiSeriesChart(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dynamicMultiSeriesChartMendixObject)
	{
		super(context, dynamicMultiSeriesChartMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Main.DynamicMultiSeriesChart", dynamicMultiSeriesChartMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Main.DynamicMultiSeriesChart");
	}

	/**
	 * @deprecated Use 'DynamicMultiSeriesChart.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static main.proxies.DynamicMultiSeriesChart initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.DynamicMultiSeriesChart.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static main.proxies.DynamicMultiSeriesChart initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.DynamicMultiSeriesChart(context, mendixObject);
	}

	public static main.proxies.DynamicMultiSeriesChart load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.DynamicMultiSeriesChart.initialize(context, mendixObject);
	}

	/**
	 * @return value of OqlQuery
	 */
	public final java.lang.String getOqlQuery()
	{
		return getOqlQuery(getContext());
	}

	/**
	 * @param context
	 * @return value of OqlQuery
	 */
	public final java.lang.String getOqlQuery(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OqlQuery.toString());
	}

	/**
	 * Set value of OqlQuery
	 * @param oqlquery
	 */
	public final void setOqlQuery(java.lang.String oqlquery)
	{
		setOqlQuery(getContext(), oqlquery);
	}

	/**
	 * Set value of OqlQuery
	 * @param context
	 * @param oqlquery
	 */
	public final void setOqlQuery(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String oqlquery)
	{
		getMendixObject().setValue(context, MemberNames.OqlQuery.toString(), oqlquery);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.DynamicMultiSeriesChart that = (main.proxies.DynamicMultiSeriesChart) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Main.DynamicMultiSeriesChart";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
