// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class DynamicChart
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dynamicChartMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.DynamicChart";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ChartName("ChartName"),
		EntityName("EntityName"),
		XValueAttributeName("XValueAttributeName"),
		XLabelAttributeName("XLabelAttributeName"),
		YValueAttribute("YValueAttribute"),
		Color("Color"),
		Label("Label"),
		SortingValue("SortingValue"),
		OqlStatement("OqlStatement"),
		JsonResult("JsonResult");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DynamicChart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Main.DynamicChart"));
	}

	protected DynamicChart(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dynamicChartMendixObject)
	{
		if (dynamicChartMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Main.DynamicChart", dynamicChartMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Main.DynamicChart");

		this.dynamicChartMendixObject = dynamicChartMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DynamicChart.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static main.proxies.DynamicChart initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.DynamicChart.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static main.proxies.DynamicChart initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.DynamicChart(context, mendixObject);
	}

	public static main.proxies.DynamicChart load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.DynamicChart.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ChartName
	 */
	public final java.lang.String getChartName()
	{
		return getChartName(getContext());
	}

	/**
	 * @param context
	 * @return value of ChartName
	 */
	public final java.lang.String getChartName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ChartName.toString());
	}

	/**
	 * Set value of ChartName
	 * @param chartname
	 */
	public final void setChartName(java.lang.String chartname)
	{
		setChartName(getContext(), chartname);
	}

	/**
	 * Set value of ChartName
	 * @param context
	 * @param chartname
	 */
	public final void setChartName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String chartname)
	{
		getMendixObject().setValue(context, MemberNames.ChartName.toString(), chartname);
	}

	/**
	 * @return value of EntityName
	 */
	public final java.lang.String getEntityName()
	{
		return getEntityName(getContext());
	}

	/**
	 * @param context
	 * @return value of EntityName
	 */
	public final java.lang.String getEntityName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EntityName.toString());
	}

	/**
	 * Set value of EntityName
	 * @param entityname
	 */
	public final void setEntityName(java.lang.String entityname)
	{
		setEntityName(getContext(), entityname);
	}

	/**
	 * Set value of EntityName
	 * @param context
	 * @param entityname
	 */
	public final void setEntityName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String entityname)
	{
		getMendixObject().setValue(context, MemberNames.EntityName.toString(), entityname);
	}

	/**
	 * @return value of XValueAttributeName
	 */
	public final java.lang.String getXValueAttributeName()
	{
		return getXValueAttributeName(getContext());
	}

	/**
	 * @param context
	 * @return value of XValueAttributeName
	 */
	public final java.lang.String getXValueAttributeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.XValueAttributeName.toString());
	}

	/**
	 * Set value of XValueAttributeName
	 * @param xvalueattributename
	 */
	public final void setXValueAttributeName(java.lang.String xvalueattributename)
	{
		setXValueAttributeName(getContext(), xvalueattributename);
	}

	/**
	 * Set value of XValueAttributeName
	 * @param context
	 * @param xvalueattributename
	 */
	public final void setXValueAttributeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xvalueattributename)
	{
		getMendixObject().setValue(context, MemberNames.XValueAttributeName.toString(), xvalueattributename);
	}

	/**
	 * @return value of XLabelAttributeName
	 */
	public final java.lang.String getXLabelAttributeName()
	{
		return getXLabelAttributeName(getContext());
	}

	/**
	 * @param context
	 * @return value of XLabelAttributeName
	 */
	public final java.lang.String getXLabelAttributeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.XLabelAttributeName.toString());
	}

	/**
	 * Set value of XLabelAttributeName
	 * @param xlabelattributename
	 */
	public final void setXLabelAttributeName(java.lang.String xlabelattributename)
	{
		setXLabelAttributeName(getContext(), xlabelattributename);
	}

	/**
	 * Set value of XLabelAttributeName
	 * @param context
	 * @param xlabelattributename
	 */
	public final void setXLabelAttributeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xlabelattributename)
	{
		getMendixObject().setValue(context, MemberNames.XLabelAttributeName.toString(), xlabelattributename);
	}

	/**
	 * @return value of YValueAttribute
	 */
	public final java.lang.String getYValueAttribute()
	{
		return getYValueAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of YValueAttribute
	 */
	public final java.lang.String getYValueAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.YValueAttribute.toString());
	}

	/**
	 * Set value of YValueAttribute
	 * @param yvalueattribute
	 */
	public final void setYValueAttribute(java.lang.String yvalueattribute)
	{
		setYValueAttribute(getContext(), yvalueattribute);
	}

	/**
	 * Set value of YValueAttribute
	 * @param context
	 * @param yvalueattribute
	 */
	public final void setYValueAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String yvalueattribute)
	{
		getMendixObject().setValue(context, MemberNames.YValueAttribute.toString(), yvalueattribute);
	}

	/**
	 * @return value of Color
	 */
	public final java.lang.String getColor()
	{
		return getColor(getContext());
	}

	/**
	 * @param context
	 * @return value of Color
	 */
	public final java.lang.String getColor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Color.toString());
	}

	/**
	 * Set value of Color
	 * @param color
	 */
	public final void setColor(java.lang.String color)
	{
		setColor(getContext(), color);
	}

	/**
	 * Set value of Color
	 * @param context
	 * @param color
	 */
	public final void setColor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String color)
	{
		getMendixObject().setValue(context, MemberNames.Color.toString(), color);
	}

	/**
	 * @return value of Label
	 */
	public final java.lang.String getLabel()
	{
		return getLabel(getContext());
	}

	/**
	 * @param context
	 * @return value of Label
	 */
	public final java.lang.String getLabel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Label.toString());
	}

	/**
	 * Set value of Label
	 * @param label
	 */
	public final void setLabel(java.lang.String label)
	{
		setLabel(getContext(), label);
	}

	/**
	 * Set value of Label
	 * @param context
	 * @param label
	 */
	public final void setLabel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String label)
	{
		getMendixObject().setValue(context, MemberNames.Label.toString(), label);
	}

	/**
	 * @return value of SortingValue
	 */
	public final java.lang.Integer getSortingValue()
	{
		return getSortingValue(getContext());
	}

	/**
	 * @param context
	 * @return value of SortingValue
	 */
	public final java.lang.Integer getSortingValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SortingValue.toString());
	}

	/**
	 * Set value of SortingValue
	 * @param sortingvalue
	 */
	public final void setSortingValue(java.lang.Integer sortingvalue)
	{
		setSortingValue(getContext(), sortingvalue);
	}

	/**
	 * Set value of SortingValue
	 * @param context
	 * @param sortingvalue
	 */
	public final void setSortingValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sortingvalue)
	{
		getMendixObject().setValue(context, MemberNames.SortingValue.toString(), sortingvalue);
	}

	/**
	 * @return value of OqlStatement
	 */
	public final java.lang.String getOqlStatement()
	{
		return getOqlStatement(getContext());
	}

	/**
	 * @param context
	 * @return value of OqlStatement
	 */
	public final java.lang.String getOqlStatement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OqlStatement.toString());
	}

	/**
	 * Set value of OqlStatement
	 * @param oqlstatement
	 */
	public final void setOqlStatement(java.lang.String oqlstatement)
	{
		setOqlStatement(getContext(), oqlstatement);
	}

	/**
	 * Set value of OqlStatement
	 * @param context
	 * @param oqlstatement
	 */
	public final void setOqlStatement(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String oqlstatement)
	{
		getMendixObject().setValue(context, MemberNames.OqlStatement.toString(), oqlstatement);
	}

	/**
	 * @return value of JsonResult
	 */
	public final java.lang.String getJsonResult()
	{
		return getJsonResult(getContext());
	}

	/**
	 * @param context
	 * @return value of JsonResult
	 */
	public final java.lang.String getJsonResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.JsonResult.toString());
	}

	/**
	 * Set value of JsonResult
	 * @param jsonresult
	 */
	public final void setJsonResult(java.lang.String jsonresult)
	{
		setJsonResult(getContext(), jsonresult);
	}

	/**
	 * Set value of JsonResult
	 * @param context
	 * @param jsonresult
	 */
	public final void setJsonResult(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String jsonresult)
	{
		getMendixObject().setValue(context, MemberNames.JsonResult.toString(), jsonresult);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dynamicChartMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.DynamicChart that = (main.proxies.DynamicChart) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Main.DynamicChart";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
