// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class DynamicMultiSeriesChartDefinition
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dynamicMultiSeriesChartDefinitionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.DynamicMultiSeriesChartDefinition";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		OqlStatement("OqlStatement"),
		JsonResult("JsonResult");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DynamicMultiSeriesChartDefinition(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Main.DynamicMultiSeriesChartDefinition"));
	}

	protected DynamicMultiSeriesChartDefinition(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dynamicMultiSeriesChartDefinitionMendixObject)
	{
		if (dynamicMultiSeriesChartDefinitionMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Main.DynamicMultiSeriesChartDefinition", dynamicMultiSeriesChartDefinitionMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Main.DynamicMultiSeriesChartDefinition");

		this.dynamicMultiSeriesChartDefinitionMendixObject = dynamicMultiSeriesChartDefinitionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DynamicMultiSeriesChartDefinition.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static main.proxies.DynamicMultiSeriesChartDefinition initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.DynamicMultiSeriesChartDefinition.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static main.proxies.DynamicMultiSeriesChartDefinition initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.DynamicMultiSeriesChartDefinition(context, mendixObject);
	}

	public static main.proxies.DynamicMultiSeriesChartDefinition load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.DynamicMultiSeriesChartDefinition.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of OqlStatement
	 */
	public final java.lang.String getOqlStatement()
	{
		return getOqlStatement(getContext());
	}

	/**
	 * @param context
	 * @return value of OqlStatement
	 */
	public final java.lang.String getOqlStatement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OqlStatement.toString());
	}

	/**
	 * Set value of OqlStatement
	 * @param oqlstatement
	 */
	public final void setOqlStatement(java.lang.String oqlstatement)
	{
		setOqlStatement(getContext(), oqlstatement);
	}

	/**
	 * Set value of OqlStatement
	 * @param context
	 * @param oqlstatement
	 */
	public final void setOqlStatement(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String oqlstatement)
	{
		getMendixObject().setValue(context, MemberNames.OqlStatement.toString(), oqlstatement);
	}

	/**
	 * @return value of JsonResult
	 */
	public final java.lang.String getJsonResult()
	{
		return getJsonResult(getContext());
	}

	/**
	 * @param context
	 * @return value of JsonResult
	 */
	public final java.lang.String getJsonResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.JsonResult.toString());
	}

	/**
	 * Set value of JsonResult
	 * @param jsonresult
	 */
	public final void setJsonResult(java.lang.String jsonresult)
	{
		setJsonResult(getContext(), jsonresult);
	}

	/**
	 * Set value of JsonResult
	 * @param context
	 * @param jsonresult
	 */
	public final void setJsonResult(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String jsonresult)
	{
		getMendixObject().setValue(context, MemberNames.JsonResult.toString(), jsonresult);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dynamicMultiSeriesChartDefinitionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.DynamicMultiSeriesChartDefinition that = (main.proxies.DynamicMultiSeriesChartDefinition) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Main.DynamicMultiSeriesChartDefinition";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
