// This file was generated by Mendix Modeler 7.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Main module
	public static mxchartutil.proxies.MultiSeriesChart createChart(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "Main.CreateChart", params);
			return result == null ? null : mxchartutil.proxies.MultiSeriesChart.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void createTestDataFromCsv(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "Main.CreateTestDataFromCsv", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void createTestDataSet(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "Main.CreateTestDataSet", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void deleteDynamicChart(IContext context, main.proxies.DynamicChart _dynamicChart, main.proxies.DynamicMultiSeriesChartDefinition _dynamicMultiSeriesChartDefinition)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DynamicChart", _dynamicChart == null ? null : _dynamicChart.getMendixObject());
			params.put("DynamicMultiSeriesChartDefinition", _dynamicMultiSeriesChartDefinition == null ? null : _dynamicMultiSeriesChartDefinition.getMendixObject());
			Core.execute(context, "Main.DeleteDynamicChart", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void entitySelected(IContext context, mxchartutil.proxies.MxEntities _mxEntities, main.proxies.DynamicChart _dynamicChart)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxEntities", _mxEntities == null ? null : _mxEntities.getMendixObject());
			params.put("DynamicChart", _dynamicChart == null ? null : _dynamicChart.getMendixObject());
			Core.execute(context, "Main.EntitySelected", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void generateChartOQL(IContext context, main.proxies.DynamicMultiSeriesChartDefinition _dynamicMultiSeriesChartDef)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DynamicMultiSeriesChartDef", _dynamicMultiSeriesChartDef == null ? null : _dynamicMultiSeriesChartDef.getMendixObject());
			Core.execute(context, "Main.GenerateChartOQL", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxchartutil.proxies.MultiSeriesChart getChartDataSet(IContext context, mxchartutil.proxies.MultiSeriesChart _multiSeriesChart)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MultiSeriesChart", _multiSeriesChart == null ? null : _multiSeriesChart.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "Main.GetChartDataSet", params);
			return result == null ? null : mxchartutil.proxies.MultiSeriesChart.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxchartutil.proxies.MultiSeriesChart getDynamicChartDataSet(IContext context, main.proxies.DynamicMultiSeriesChart _multiSeriesChart)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MultiSeriesChart", _multiSeriesChart == null ? null : _multiSeriesChart.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "Main.GetDynamicChartDataSet", params);
			return result == null ? null : mxchartutil.proxies.MultiSeriesChart.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<main.proxies.DynamicChart> getDynamicCharts(IContext context, main.proxies.DynamicMultiSeriesChartDefinition _dynamicChart)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DynamicChart", _dynamicChart == null ? null : _dynamicChart.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "Main.GetDynamicCharts", params);
			java.util.List<main.proxies.DynamicChart> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<main.proxies.DynamicChart>();
				for (IMendixObject obj : objs)
					result.add(main.proxies.DynamicChart.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxchartutil.proxies.MxEntities> getEntities(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.List<IMendixObject> objs = Core.execute(context, "Main.GetEntities", params);
			java.util.List<mxchartutil.proxies.MxEntities> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxchartutil.proxies.MxEntities>();
				for (IMendixObject obj : objs)
					result.add(mxchartutil.proxies.MxEntities.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void getJsonForOqlChartQuery(IContext context, main.proxies.DynamicMultiSeriesChartDefinition _dynamicChartDef)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DynamicChartDef", _dynamicChartDef == null ? null : _dynamicChartDef.getMendixObject());
			Core.execute(context, "Main.GetJsonForOqlChartQuery", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mapJsonToObjects(IContext context, main.proxies.DynamicMultiSeriesChartDefinition _dynamicMultiSeriesChart)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DynamicMultiSeriesChart", _dynamicMultiSeriesChart == null ? null : _dynamicMultiSeriesChart.getMendixObject());
			Core.execute(context, "Main.MapJsonToObjects", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static main.proxies.DynamicChart newDynamicChart(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "Main.NewDynamicChart", params);
			return result == null ? null : main.proxies.DynamicChart.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static main.proxies.DynamicChart newDynamicChart2(IContext context, main.proxies.DynamicMultiSeriesChartDefinition _dynamicMultiSeriesChartDefinition)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DynamicMultiSeriesChartDefinition", _dynamicMultiSeriesChartDefinition == null ? null : _dynamicMultiSeriesChartDefinition.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "Main.NewDynamicChart2", params);
			return result == null ? null : main.proxies.DynamicChart.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static main.proxies.DynamicMultiSeriesChartDefinition newDynamicMultiSeriesChart(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "Main.NewDynamicMultiSeriesChart", params);
			return result == null ? null : main.proxies.DynamicMultiSeriesChartDefinition.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void saveDynamicChart(IContext context, main.proxies.DynamicChart _dynamicChart, main.proxies.DynamicMultiSeriesChartDefinition _dynamicMultiSeriesChartDefinition)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DynamicChart", _dynamicChart == null ? null : _dynamicChart.getMendixObject());
			params.put("DynamicMultiSeriesChartDefinition", _dynamicMultiSeriesChartDefinition == null ? null : _dynamicMultiSeriesChartDefinition.getMendixObject());
			Core.execute(context, "Main.SaveDynamicChart", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mxchartutil.proxies.MultiSeriesChart showChartPopup(IContext context, main.proxies.DynamicMultiSeriesChartDefinition _dynamicMultiSeriesChartDef)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DynamicMultiSeriesChartDef", _dynamicMultiSeriesChartDef == null ? null : _dynamicMultiSeriesChartDef.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "Main.ShowChartPopup", params);
			return result == null ? null : mxchartutil.proxies.MultiSeriesChart.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void testOQLToDatasetEntity(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "Main.TestOQLToDatasetEntity", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void xlabelAttributeSelected(IContext context, mxchartutil.proxies.MxEntityAttributes _mxEntityAttributes, main.proxies.DynamicChart _dynamicChart)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxEntityAttributes", _mxEntityAttributes == null ? null : _mxEntityAttributes.getMendixObject());
			params.put("DynamicChart", _dynamicChart == null ? null : _dynamicChart.getMendixObject());
			Core.execute(context, "Main.XlabelAttributeSelected", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxchartutil.proxies.MxEntityAttributes> xlabelGetEntityAttributes(IContext context, main.proxies.DynamicChart _dynamicChart)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DynamicChart", _dynamicChart == null ? null : _dynamicChart.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "Main.XlabelGetEntityAttributes", params);
			java.util.List<mxchartutil.proxies.MxEntityAttributes> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxchartutil.proxies.MxEntityAttributes>();
				for (IMendixObject obj : objs)
					result.add(mxchartutil.proxies.MxEntityAttributes.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void xValueAttributeSelected(IContext context, mxchartutil.proxies.MxEntityAttributes _mxEntityAttributes, main.proxies.DynamicChart _dynamicChart)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxEntityAttributes", _mxEntityAttributes == null ? null : _mxEntityAttributes.getMendixObject());
			params.put("DynamicChart", _dynamicChart == null ? null : _dynamicChart.getMendixObject());
			Core.execute(context, "Main.XValueAttributeSelected", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxchartutil.proxies.MxEntityAttributes> xValueGetEntityAttributes(IContext context, main.proxies.DynamicChart _dynamicChart)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DynamicChart", _dynamicChart == null ? null : _dynamicChart.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "Main.XValueGetEntityAttributes", params);
			java.util.List<mxchartutil.proxies.MxEntityAttributes> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxchartutil.proxies.MxEntityAttributes>();
				for (IMendixObject obj : objs)
					result.add(mxchartutil.proxies.MxEntityAttributes.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void yValueAttributeSelected(IContext context, mxchartutil.proxies.MxEntityAttributes _mxEntityAttributes, main.proxies.DynamicChart _dynamicChart)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MxEntityAttributes", _mxEntityAttributes == null ? null : _mxEntityAttributes.getMendixObject());
			params.put("DynamicChart", _dynamicChart == null ? null : _dynamicChart.getMendixObject());
			Core.execute(context, "Main.YValueAttributeSelected", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxchartutil.proxies.MxEntityAttributes> yValueGetEntityAttributes(IContext context, main.proxies.DynamicChart _dynamicChart)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DynamicChart", _dynamicChart == null ? null : _dynamicChart.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "Main.YValueGetEntityAttributes", params);
			java.util.List<mxchartutil.proxies.MxEntityAttributes> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxchartutil.proxies.MxEntityAttributes>();
				for (IMendixObject obj : objs)
					result.add(mxchartutil.proxies.MxEntityAttributes.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}