// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxchartutil.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaObject;
import com.mendix.webui.CustomJavaAction;
import mxchartutil.proxies.MxEntities;
import java.util.ArrayList;

public class GetEntities extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String Module;

	public GetEntities(IContext context, java.lang.String Module)
	{
		super(context);
		this.Module = Module;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
        ArrayList<IMendixObject> entities = new ArrayList<IMendixObject>();
        Iterable<IMetaObject> metaObjectsIter = Core.getMetaObjects();
        metaObjectsIter.forEach(meta -> {
            String moduleName = meta.getModuleName();
            String entityName = meta.getName();
            MxEntities entityObj = new MxEntities(getContext());
            entityObj.setModuleName(moduleName);
            entityObj.setEntityName(entityName);
            entities.add(entityObj.getMendixObject());
        });
        return entities;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetEntities";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
