// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxchartutil.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GetEntityAttributes extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String ModuleName;
	private java.lang.String EntityName;
	private java.lang.String AttributeName;

	public GetEntityAttributes(IContext context, java.lang.String ModuleName, java.lang.String EntityName, java.lang.String AttributeName)
	{
		super(context);
		this.ModuleName = ModuleName;
		this.EntityName = EntityName;
		this.AttributeName = AttributeName;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetEntityAttributes";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
