// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxchartutil.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaPrimitive;
import com.mendix.webui.CustomJavaAction;
import mxchartutil.proxies.MxEntityAttributes;
import java.util.ArrayList;
import java.util.Collection;

public class GetEntityAttributes extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String EntityName;
	private java.lang.String AttributeName;

	public GetEntityAttributes(IContext context, java.lang.String EntityName, java.lang.String AttributeName)
	{
		super(context);
		this.EntityName = EntityName;
		this.AttributeName = AttributeName;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
        ArrayList<IMendixObject> attributes = new ArrayList<IMendixObject>();
        Collection<IMetaPrimitive> metaObjectsIter = (Collection<IMetaPrimitive>) Core.getMetaObject(this.EntityName).getMetaPrimitives();
        metaObjectsIter.forEach(meta -> {
            String primitiveName = meta.getName();
            String entityName = meta.getParent().getName();
            MxEntityAttributes attrObj = new MxEntityAttributes(getContext());
            attrObj.setEntityName(entityName);
            attrObj.setAttributeName(primitiveName);
            attrObj.setAttributeType(meta.getType().name());
            attributes.add(attrObj.getMendixObject());
        });
        return attributes;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetEntityAttributes";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
